// Compile the contracts this launch deploys and write them where a wallet and a browser can
// both reach them.
//
//   node deploy/scripts/artifacts.mjs
//
// Writes deploy/artifacts.json (what build.mjs reads, and what test/run-deploy.mjs checks a
// fresh compile against) and deploy/artifacts.js (the same object as a global, because
// deploy/deploy.html has to work from a file:// URL where fetch() of a sibling file is blocked
// by the browser and a classic <script src> is not).
//
// Regenerate rather than edit — the same instruction deploy/README.md gives about the files
// test/run-deployable.mjs writes, for the same reason. The ground address is derived from
// these bytes.
import fs from "node:fs";
import { artifacts, ARTIFACTS_JSON, ARTIFACTS_JS, SETTINGS, DEPLOYABLE } from "./lib/solc.mjs";
import { loadConfig } from "./lib/config.mjs";

const { artifacts: a, warnings } = artifacts();
if (warnings.length) {
  console.error("compiled with warnings, refusing to write:");
  for (const w of warnings) console.error("  " + w.message.split("\n")[0]);
  process.exit(1);
}

// Checked BEFORE the first write, not between the two. The first version validated the config
// after artifacts.json had already been written, so a bad config left the two files holding
// different compiles under a message saying it had refused to write.
const cfg = loadConfig();
if (cfg.problems.length) {
  console.error("deploy/config.json has problems, refusing to write artifacts:");
  for (const p of cfg.problems) console.error("  · " + p);
  process.exit(1);
}

fs.writeFileSync(ARTIFACTS_JSON, JSON.stringify(a, null, 2) + "\n");

// The browser twin carries the same compile output PLUS the launch parameters, because
// deploy/deploy.html cannot read deploy/config.json either: under a file:// URL fetch() of a
// sibling file is blocked, and a classic <script src> is not. Everything here is already
// public — it is the same file config.json is, plus bytecode — and there is no endpoint in it.
//
// The parameters are the RESOLVED ones, so the page cannot re-derive them differently: the
// bigints are stringified, gateUntil is the value config.mjs computed, and the checks
// config.mjs ran have already passed by the time this is written.
const str = v => (typeof v === "bigint" ? v.toString() : v);
const launch = {
  chainId: cfg.chainId,
  owner: cfg.owner,
  token: { ...cfg.token, supply: str(cfg.token.supply) },
  curve: Object.fromEntries(Object.entries(cfg.curve).map(([k, v]) => [k, str(v)])),
  vanity: cfg.vanity,
  oracle: { choice: cfg.oracle.choice, address: cfg.oracle.address,
            describe: cfg.oracle.describe },
};
fs.writeFileSync(ARTIFACTS_JS,
  "/* Generated by deploy/scripts/artifacts.mjs. Do not edit — regenerate.\n" +
  "   deploy/deploy.html loads this with a classic <script src>, which works from a file://\n" +
  "   URL where fetch() of a sibling file does not. There is no endpoint or key in here. */\n" +
  "window.__SNOOZE = " + JSON.stringify({ ...a, launch }, null, 2) + ";\n");

console.log(`solc ${SETTINGS.version}, optimizer ${SETTINGS.optimizer ? "on" : "off"}, ` +
            `${SETTINGS.runs} runs`);
for (const n of DEPLOYABLE) {
  const c = a.contracts[n];
  console.log(`  ${n.padEnd(16)} init ${String(c.initCodeBytes).padStart(6)}  ` +
              `runtime ${String(c.runtimeBytes).padStart(6)}  ${c.constructorInputs.join(", ")}`);
}
console.log(`\nwrote ${ARTIFACTS_JSON}`);
console.log(`wrote ${ARTIFACTS_JS}`);
